# Generated by Django 4.2.13 on 2024-07-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reserved', 'Reserved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
